import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {TheHeader} from "./components/TheHeader";

import {Toaster} from "react-hot-toast";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <TheHeader/>
    <div className="flex justify-center mt-9 ">
      <main className="flex flex-col items-center gap-10 w-[80%]">
        {children}
      </main>
    </div>
    <Toaster/>
    </body>
    </html>
  );
}
